ref: docker
name: docker
description: Docker Container integrations
keywords:
- docker
- containers
- virtualization
- cgroups
version: 0.3.2
author: StackStorm, Inc.
email: info@stackstorm.com
content:
  actions:
    count: 3
    resources:
    - pull_image
    - push_image
    - build_image
  sensors:
    count: 1
    resources:
    - DockerSensor
  tests:
    count: 1
    resources:
    - test_sensor_docker_sensor.py
