ref: kubernetes
name: kubernetes
description: Kubernetes actions and sensors
keywords:
- kubernetes
- sensors
- thirdpartyresource
version: 0.9.7
author: Andrew Moore
email: andy@impulsed.net
contributors:
- Michael Ward <mward29@gmail.com>
content:
  actions:
    count: 366
    resources:
    - deleteExtensionsV1beta1CollectionNamespacedDeployment
    - listAppsV1beta1StatefulSetForAllNamespaces
    - patchPolicyV1beta1NamespacedPodDisruptionBudgetStatus
    - listCoreV1NamespacedLimitRange
    - listCoreV1ServiceAccountForAllNamespaces
    - patchCoreV1NamespacedPodStatus
    - patchCoreV1NamespacedSecret
    - patchExtensionsV1beta1NamespacedNetworkPolicy
    - listPolicyV1beta1NamespacedPodDisruptionBudget
    - listBatchV1JobForAllNamespaces
    - createCoreV1NamespacedEvictionEviction
    - createCoreV1NamespacedPersistentVolumeClaim
    - deleteRbacAuthorizationV1alpha1CollectionNamespacedRole
    - register_sensor
    - replaceExtensionsV1beta1NamespacedDeploymentsScale
    - listCoreV1Node
    - readCoreV1NamespacedResourceQuota
    - replaceCoreV1NamespacedServiceAccount
    - createRbacAuthorizationV1alpha1NamespacedRoleBinding
    - replaceCoreV1NamespacedResourceQuota
    - deleteRbacAuthorizationV1alpha1CollectionClusterRole
    - listCoreV1PodTemplateForAllNamespaces
    - patchCoreV1PersistentVolume
    - deleteRbacAuthorizationV1alpha1ClusterRole
    - patchExtensionsV1beta1NamespacedDeploymentStatus
    - deleteAutoscalingV1NamespacedHorizontalPodAutoscaler
    - deleteExtensionsV1beta1CollectionThirdPartyResource
    - deleteCoreV1NamespacedService
    - createCoreV1NamespacedConfigMap
    - listCoreV1NamespacedPod
    - deletePolicyV1beta1CollectionNamespacedPodDisruptionBudget
    - createAuthenticationV1beta1TokenReview
    - readExtensionsV1beta1NamespacedReplicasetsScale
    - deleteRbacAuthorizationV1alpha1CollectionClusterRoleBinding
    - readExtensionsV1beta1NamespacedDeploymentsScale
    - getRbacAuthorizationAPIGroup
    - createExtensionsV1beta1NamespacedHorizontalPodAutoscaler
    - patchExtensionsV1beta1NamespacedReplicaSetStatus
    - replaceCoreV1NamespacedPodTemplate
    - createCoreV1NamespacedBindingBinding
    - deleteCoreV1CollectionNamespacedPersistentVolumeClaim
    - readCoreV1NamespacedSecret
    - createBatchV1NamespacedJob
    - listExtensionsV1beta1NetworkPolicyForAllNamespaces
    - readCoreV1Namespace
    - readCoreV1NamespacedScaleScale
    - createTPR
    - listRbacAuthorizationV1alpha1ClusterRoleBinding
    - createExtensionsV1beta1NamespacedJob
    - listCertificatesV1alpha1CertificateSigningRequest
    - listCoreV1ConfigMapForAllNamespaces
    - createCoreV1NamespacedReplicationController
    - patchStorageV1beta1StorageClass
    - deleteCoreV1NamespacedPod
    - listCoreV1NamespacedEndpoints
    - deleteExtensionsV1beta1NamespacedReplicaSet
    - patchCoreV1NamespacedEndpoints
    - listCoreV1NamespacedReplicationController
    - patchCoreV1NamespacedScaleScale
    - getAutoscalingV1APIResources
    - patchExtensionsV1beta1NamespacedIngressStatus
    - readExtensionsV1beta1NamespacedNetworkPolicy
    - getCoreAPIVersions
    - createCoreV1PersistentVolume
    - patchCoreV1NamespacedPodTemplate
    - deleteExtensionsV1beta1NamespacedHorizontalPodAutoscaler
    - readCoreV1NodeStatus
    - createCoreV1NamespacedEvent
    - getAuthorizationV1beta1APIResources
    - replaceAutoscalingV1NamespacedHorizontalPodAutoscalerStatus
    - readAppsV1beta1NamespacedStatefulSet
    - replaceCoreV1NamespacedPodStatus
    - replaceCoreV1Node
    - readCoreV1NamespacedLimitRange
    - listRbacAuthorizationV1alpha1RoleBindingForAllNamespaces
    - createRbacAuthorizationV1alpha1ClusterRoleBinding
    - readBatchV1NamespacedJob
    - patchExtensionsV1beta1NamespacedIngress
    - deleteExtensionsV1beta1NamespacedJob
    - patchExtensionsV1beta1NamespacedReplicationcontrollersScale
    - listRbacAuthorizationV1alpha1NamespacedRoleBinding
    - listCoreV1ReplicationControllerForAllNamespaces
    - listCoreV1ResourceQuotaForAllNamespaces
    - patchRbacAuthorizationV1alpha1ClusterRoleBinding
    - getAuthorizationAPIGroup
    - listExtensionsV1beta1NamespacedReplicaSet
    - deleteExtensionsV1beta1NamespacedDeployment
    - createRbacAuthorizationV1alpha1ClusterRole
    - readRbacAuthorizationV1alpha1ClusterRole
    - deleteCoreV1Node
    - createAuthorizationV1beta1NamespacedLocalSubjectAccessReview
    - readCertificatesV1alpha1CertificateSigningRequest
    - replaceCoreV1Namespace
    - readRbacAuthorizationV1alpha1NamespacedRoleBinding
    - listExtensionsV1beta1HorizontalPodAutoscalerForAllNamespaces
    - deleteExtensionsV1beta1CollectionNamespacedIngress
    - readCoreV1NamespaceStatus
    - readExtensionsV1beta1NamespacedReplicationcontrollersScale
    - listExtensionsV1beta1DaemonSetForAllNamespaces
    - getCoreV1APIResources
    - listExtensionsV1beta1NamespacedDeployment
    - deleteCoreV1Namespace
    - patchCertificatesV1alpha1CertificateSigningRequest
    - replaceCoreV1NamespacedScaleScale
    - listCoreV1NamespacedSecret
    - getStorageV1beta1APIResources
    - patchExtensionsV1beta1NamespacedHorizontalPodAutoscaler
    - patchCoreV1NamespacedReplicationController
    - readPolicyV1beta1NamespacedPodDisruptionBudgetStatus
    - patchCoreV1NamespacedPersistentVolumeClaimStatus
    - replaceExtensionsV1beta1NamespacedIngress
    - listCoreV1PodForAllNamespaces
    - patchExtensionsV1beta1NamespacedReplicaSet
    - replaceExtensionsV1beta1NamespacedHorizontalPodAutoscaler
    - createRbacAuthorizationV1alpha1NamespacedRole
    - getCertificatesAPIGroup
    - replaceCoreV1NamespaceStatus
    - listExtensionsV1beta1JobForAllNamespaces
    - deleteCoreV1NamespacedReplicationController
    - listExtensionsV1beta1DeploymentForAllNamespaces
    - deleteExtensionsV1beta1NamespacedIngress
    - delete_tpr_sensor
    - getBatchAPIGroup
    - patchBatchV1NamespacedJobStatus
    - deleteExtensionsV1beta1CollectionNamespacedDaemonSet
    - replaceExtensionsV1beta1NamespacedHorizontalPodAutoscalerStatus
    - patchPolicyV1beta1NamespacedPodDisruptionBudget
    - replaceCoreV1NamespacedEvent
    - replaceCoreV1NamespacedReplicationControllerStatus
    - createAppsV1beta1NamespacedStatefulSet
    - readCoreV1PersistentVolume
    - listCoreV1EndpointsForAllNamespaces
    - deleteExtensionsV1beta1NamespacedDaemonSet
    - listCoreV1LimitRangeForAllNamespaces
    - replaceCoreV1NamespacedSecret
    - readExtensionsV1beta1NamespacedDeploymentStatus
    - listAppsV1beta1NamespacedStatefulSet
    - replaceCoreV1NamespacedPod
    - replacePolicyV1beta1NamespacedPodDisruptionBudget
    - replaceCoreV1PersistentVolume
    - replaceRbacAuthorizationV1alpha1NamespacedRoleBinding
    - readExtensionsV1beta1NamespacedHorizontalPodAutoscaler
    - deleteCoreV1CollectionNamespacedSecret
    - deleteRbacAuthorizationV1alpha1NamespacedRole
    - readExtensionsV1beta1NamespacedDaemonSetStatus
    - deleteCoreV1NamespacedPodTemplate
    - patchCoreV1PersistentVolumeStatus
    - listCoreV1Namespace
    - deleteCoreV1CollectionNamespacedLimitRange
    - create_tpr_sensor
    - patchExtensionsV1beta1NamespacedDeploymentsScale
    - deleteCoreV1NamespacedConfigMap
    - createCoreV1NamespacedLimitRange
    - patchRbacAuthorizationV1alpha1NamespacedRoleBinding
    - deleteCoreV1NamespacedEndpoints
    - replaceExtensionsV1beta1NamespacedIngressStatus
    - readStorageV1beta1StorageClass
    - createCoreV1NamespacedPod
    - deleteCoreV1CollectionNamespacedEvent
    - patchCoreV1NamespacedResourceQuota
    - patchExtensionsV1beta1NamespacedJobStatus
    - listCoreV1SecretForAllNamespaces
    - patchCoreV1NamespacedPersistentVolumeClaim
    - deleteCoreV1PersistentVolume
    - createExtensionsV1beta1NamespacedDeploymentRollbackRollback
    - deleteStorageV1beta1StorageClass
    - deleteCoreV1CollectionNamespacedEndpoints
    - getBatchV1APIResources
    - createExtensionsV1beta1NamespacedReplicaSet
    - readExtensionsV1beta1NamespacedReplicaSet
    - replaceExtensionsV1beta1NamespacedReplicationcontrollersScale
    - replaceCoreV1NamespacedPersistentVolumeClaimStatus
    - readAutoscalingV1NamespacedHorizontalPodAutoscaler
    - readCoreV1PersistentVolumeStatus
    - createCoreV1NamespacedEndpoints
    - patchExtensionsV1beta1NamespacedDeployment
    - readCoreV1NamespacedResourceQuotaStatus
    - createCoreV1NamespacedPodTemplate
    - replaceExtensionsV1beta1ThirdPartyResource
    - listCoreV1NamespacedResourceQuota
    - getAppsAPIGroup
    - replaceCoreV1NamespacedServiceStatus
    - readCoreV1NamespacedEndpoints
    - replaceExtensionsV1beta1NamespacedJob
    - getRbacAuthorizationV1alpha1APIResources
    - listRbacAuthorizationV1alpha1ClusterRole
    - listAllTPR
    - patchExtensionsV1beta1ThirdPartyResource
    - deleteAppsV1beta1NamespacedStatefulSet
    - createExtensionsV1beta1ThirdPartyResource
    - replaceExtensionsV1beta1NamespacedNetworkPolicy
    - getAuthenticationV1beta1APIResources
    - replaceRbacAuthorizationV1alpha1ClusterRoleBinding
    - patchCoreV1Namespace
    - createExtensionsV1beta1NamespacedNetworkPolicy
    - listCoreV1ComponentStatus
    - getStorageAPIGroup
    - replaceCertificatesV1alpha1CertificateSigningRequestStatus
    - replaceCoreV1NamespacedConfigMap
    - readCoreV1Node
    - readRbacAuthorizationV1alpha1NamespacedRole
    - patchCoreV1NamespacedServiceStatus
    - check_sensor_list
    - patchRbacAuthorizationV1alpha1ClusterRole
    - deleteCoreV1CollectionNamespacedPod
    - createAuthorizationV1beta1SelfSubjectAccessReview
    - deleteExtensionsV1beta1NamespacedNetworkPolicy
    - replaceExtensionsV1beta1NamespacedDeploymentStatus
    - patchCoreV1NamespaceStatus
    - patchAppsV1beta1NamespacedStatefulSetStatus
    - deleteRbacAuthorizationV1alpha1NamespacedRoleBinding
    - replaceAppsV1beta1NamespacedStatefulSet
    - createCoreV1NamespacedResourceQuota
    - getBatchV2alpha1APIResources
    - replaceExtensionsV1beta1NamespacedDaemonSet
    - deleteCoreV1NamespacedPersistentVolumeClaim
    - readCoreV1ComponentStatus
    - patchCoreV1NodeStatus
    - createExtensionsV1beta1NamespacedIngress
    - listCoreV1PersistentVolumeClaimForAllNamespaces
    - replaceAppsV1beta1NamespacedStatefulSetStatus
    - readCoreV1NamespacedPersistentVolumeClaim
    - patchRbacAuthorizationV1alpha1NamespacedRole
    - replaceCoreV1PersistentVolumeStatus
    - replaceCoreV1NamespacedEndpoints
    - deleteCoreV1CollectionNamespacedConfigMap
    - patchExtensionsV1beta1NamespacedDaemonSet
    - listPolicyV1beta1PodDisruptionBudgetForAllNamespaces
    - replaceRbacAuthorizationV1alpha1NamespacedRole
    - replaceCoreV1NamespacedResourceQuotaStatus
    - deleteCoreV1CollectionNamespacedResourceQuota
    - listCoreV1NamespacedEvent
    - readBatchV1NamespacedJobStatus
    - readCoreV1NamespacedPodStatus
    - deleteCoreV1CollectionNamespacedReplicationController
    - replaceCertificatesV1alpha1CertificateSigningRequest
    - listExtensionsV1beta1ReplicaSetForAllNamespaces
    - patchExtensionsV1beta1NamespacedJob
    - deleteExtensionsV1beta1ThirdPartyResource
    - patchExtensionsV1beta1NamespacedDaemonSetStatus
    - readCoreV1NamespacedServiceAccount
    - listExtensionsV1beta1IngressForAllNamespaces
    - listExtensionsV1beta1NamespacedNetworkPolicy
    - listCoreV1EventForAllNamespaces
    - replaceCoreV1NodeStatus
    - getAppsV1beta1APIResources
    - readCoreV1NamespacedPod
    - deletePolicyV1beta1NamespacedPodDisruptionBudget
    - listBatchV1NamespacedJob
    - replaceCoreV1NamespacedLimitRange
    - replaceExtensionsV1beta1NamespacedReplicasetsScale
    - readCoreV1NamespacedServiceStatus
    - listAutoscalingV1HorizontalPodAutoscalerForAllNamespaces
    - readCoreV1NamespacedService
    - listExtensionsV1beta1NamespacedHorizontalPodAutoscaler
    - readExtensionsV1beta1NamespacedDeployment
    - deleteCoreV1CollectionNode
    - patchCoreV1NamespacedConfigMap
    - patchCoreV1NamespacedLimitRange
    - patchCoreV1NamespacedServiceAccount
    - createExtensionsV1beta1NamespacedDeployment
    - getPolicyV1beta1APIResources
    - listCoreV1NamespacedService
    - readExtensionsV1beta1NamespacedJobStatus
    - deleteCoreV1NamespacedResourceQuota
    - deleteCertificatesV1alpha1CertificateSigningRequest
    - readExtensionsV1beta1NamespacedDaemonSet
    - listStorageV1beta1StorageClass
    - readCoreV1NamespacedReplicationControllerStatus
    - patchAutoscalingV1NamespacedHorizontalPodAutoscalerStatus
    - deleteCoreV1NamespacedSecret
    - deleteCoreV1CollectionNamespacedServiceAccount
    - deleteAppsV1beta1CollectionNamespacedStatefulSet
    - createAuthorizationV1beta1SubjectAccessReview
    - createCoreV1NamespacedBinding
    - readExtensionsV1beta1NamespacedIngressStatus
    - listExtensionsV1beta1NamespacedIngress
    - readRbacAuthorizationV1alpha1ClusterRoleBinding
    - listCoreV1NamespacedPodTemplate
    - patchBatchV1NamespacedJob
    - listCoreV1NamespacedConfigMap
    - createCoreV1NamespacedServiceAccount
    - patchAppsV1beta1NamespacedStatefulSet
    - patchCoreV1NamespacedResourceQuotaStatus
    - replaceExtensionsV1beta1NamespacedReplicaSetStatus
    - patchCoreV1NamespacedService
    - patchCoreV1NamespacedPod
    - replaceRbacAuthorizationV1alpha1ClusterRole
    - patchCoreV1NamespacedEvent
    - deleteBatchV1CollectionNamespacedJob
    - register_tpr
    - getAutoscalingAPIGroup
    - createCertificatesV1alpha1CertificateSigningRequest
    - deleteRbacAuthorizationV1alpha1CollectionNamespacedRoleBinding
    - createCoreV1Namespace
    - replaceBatchV1NamespacedJob
    - deleteStorageV1beta1CollectionStorageClass
    - listExtensionsV1beta1NamespacedJob
    - replaceExtensionsV1beta1NamespacedJobStatus
    - listCoreV1ServiceForAllNamespaces
    - deleteExtensionsV1beta1CollectionNamespacedReplicaSet
    - deleteCoreV1NamespacedLimitRange
    - deleteCoreV1NamespacedServiceAccount
    - readExtensionsV1beta1NamespacedReplicaSetStatus
    - deleteCoreV1CollectionNamespace
    - listExtensionsV1beta1NamespacedDaemonSet
    - getPolicyAPIGroup
    - getAPIVersions
    - listCoreV1PersistentVolume
    - deleteCoreV1NamespacedEvent
    - listAutoscalingV1NamespacedHorizontalPodAutoscaler
    - readExtensionsV1beta1NamespacedJob
    - readCoreV1NamespacedPodTemplate
    - getExtensionsV1beta1APIResources
    - patchCoreV1Node
    - patchCoreV1NamespacedReplicationControllerStatus
    - createCoreV1NamespacedSecret
    - readCoreV1NamespacedReplicationController
    - createStorageV1beta1StorageClass
    - deleteRbacAuthorizationV1alpha1ClusterRoleBinding
    - readAppsV1beta1NamespacedStatefulSetStatus
    - deleteCoreV1CollectionNamespacedPodTemplate
    - createPolicyV1beta1NamespacedPodDisruptionBudget
    - getAuthenticationAPIGroup
    - listRbacAuthorizationV1alpha1RoleForAllNamespaces
    - replaceCoreV1NamespacedPersistentVolumeClaim
    - deleteCoreV1CollectionPersistentVolume
    - replaceCoreV1NamespaceFinalize
    - deleteAutoscalingV1CollectionNamespacedHorizontalPodAutoscaler
    - deleteCertificatesV1alpha1CollectionCertificateSigningRequest
    - readExtensionsV1beta1NamespacedHorizontalPodAutoscalerStatus
    - replaceExtensionsV1beta1NamespacedReplicaSet
    - createCoreV1NamespacedService
    - replaceCoreV1NamespacedService
    - replacePolicyV1beta1NamespacedPodDisruptionBudgetStatus
    - readCoreV1NamespacedEvent
    - patchExtensionsV1beta1NamespacedReplicasetsScale
    - createExtensionsV1beta1NamespacedDaemonSet
    - replaceAutoscalingV1NamespacedHorizontalPodAutoscaler
    - createCoreV1Node
    - replaceExtensionsV1beta1NamespacedDeployment
    - patchAutoscalingV1NamespacedHorizontalPodAutoscaler
    - listCoreV1NamespacedPersistentVolumeClaim
    - deleteExtensionsV1beta1CollectionNamespacedHorizontalPodAutoscaler
    - readExtensionsV1beta1NamespacedIngress
    - patchExtensionsV1beta1NamespacedHorizontalPodAutoscalerStatus
    - readCoreV1NamespacedConfigMap
    - deleteBatchV1NamespacedJob
    - deleteExtensionsV1beta1CollectionNamespacedNetworkPolicy
    - replaceExtensionsV1beta1NamespacedDaemonSetStatus
    - readExtensionsV1beta1ThirdPartyResource
    - createAutoscalingV1NamespacedHorizontalPodAutoscaler
    - readPolicyV1beta1NamespacedPodDisruptionBudget
    - replaceStorageV1beta1StorageClass
    - getCertificatesV1alpha1APIResources
    - listExtensionsV1beta1ThirdPartyResource
    - deleteExtensionsV1beta1CollectionNamespacedJob
    - readAutoscalingV1NamespacedHorizontalPodAutoscalerStatus
    - listRbacAuthorizationV1alpha1NamespacedRole
    - readCoreV1NamespacedPersistentVolumeClaimStatus
    - replaceBatchV1NamespacedJobStatus
    - replaceCertificatesV1alpha1CertificateSigningRequestApproval
    - readCoreV1NamespacedPodLog
    - getExtensionsAPIGroup
    - replaceCoreV1NamespacedReplicationController
    - listCoreV1NamespacedServiceAccount
  rules:
    count: 2
    resources:
    - kubernetes_third_party_resource_delete
    - kubernetes_third_party_resource_create
  sensors:
    count: 33
    resources:
    - watchAutoscalingV1HorizontalPodAutoscalerListForAllNamespaces
    - watchExtensionsV1beta1JobListForAllNamespaces
    - watchExtensionsV1beta1IngressListForAllNamespaces
    - watchCoreV1EndpointsListForAllNamespaces
    - watchExtensionsV1beta1ThirdPartyResourceList
    - watchBatchV1JobListForAllNamespaces
    - watchExtensionsV1beta1NetworkPolicyListForAllNamespaces
    - watchPolicyV1beta1PodDisruptionBudgetListForAllNamespaces
    - watchExtensionsV1beta1ReplicaSetListForAllNamespaces
    - watchRbacAuthorizationV1alpha1RoleListForAllNamespaces
    - watchRbacAuthorizationV1alpha1ClusterRoleBindingList
    - watchCoreV1ConfigMapListForAllNamespaces
    - watchCoreV1EventListForAllNamespaces
    - watchCoreV1NamespaceList
    - watchCertificatesV1alpha1CertificateSigningRequestList
    - watchCoreV1SecretListForAllNamespaces
    - watchCoreV1ReplicationControllerListForAllNamespaces
    - watchCoreV1PersistentVolumeClaimListForAllNamespaces
    - watchRbacAuthorizationV1alpha1RoleBindingListForAllNamespaces
    - watchCoreV1LimitRangeListForAllNamespaces
    - watchCoreV1ResourceQuotaListForAllNamespaces
    - watchCoreV1ServiceListForAllNamespaces
    - watchExtensionsV1beta1DeploymentListForAllNamespaces
    - watchRbacAuthorizationV1alpha1ClusterRoleList
    - watchCoreV1ServiceAccountListForAllNamespaces
    - watchCoreV1PodTemplateListForAllNamespaces
    - watchCoreV1PersistentVolumeList
    - watchCoreV1NodeList
    - watchExtensionsV1beta1HorizontalPodAutoscalerListForAllNamespaces
    - watchStorageV1beta1StorageClassList
    - watchCoreV1PodListForAllNamespaces
    - watchExtensionsV1beta1DaemonSetListForAllNamespaces
    - watchAppsV1beta1StatefulSetListForAllNamespaces
