name: prometheus
ref: prometheus
description: Interact with Prometheus HTTP API
keywords:
- prometheus
version: 0.1.2
author: Daniel Chamot
email: daniel@nullkarma.com
content:
  actions:
    count: 3
