name: Enable Pack Release

# Only allow one workflow run per branch at a time.
# When one is already running, new runs will be pending.
# https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
concurrency:
  group: enable-pack-release-${{ github.ref }}
  # Do not use cancel-in-progress! Or we might create a scenario where all workflows get canceled before they complete.

permissions:
  contents: write

on:
  # First day of the month at midnight.
  schedule:
    - cron:  "0 0 1 * *"
  # manual rebuilds by TSC members
  workflow_dispatch:

jobs:
  enable_pack_release_workflow:
    name: 'Enable Pack Release Workflow'
    uses: StackStorm-Exchange/ci/.github/workflows/pack-enable_release_workflow.yaml@master
