name: Update Index

# Only allow one workflow run per branch at a time.
# When one is already running, new runs will be pending.
# https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
concurrency:
  group: index-update-${{ github.ref }}
  # Do not use cancel-in-progress! Or we might create a scenario where all workflows get canceled before they complete.

permissions:
  contents: write

on:
  # every 5 minutes. Increase time if workflows are overlapping.
  schedule:
    - cron:  '*/5 * * * *'
  # manual rebuilds by TSC members
  workflow_dispatch:

jobs:

  enable_pack_release_workflow:
    name: 'Enable Pack Release Workflow'
    uses: StackStorm-Exchange/ci/.github/workflows/pack-enable_release_workflow.yaml@master

  update_index:
    name: 'Update Index'
    uses: StackStorm-Exchange/ci/.github/workflows/index-update.yaml@master
